on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  tag:
    name: Tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch "main"
        uses: actions/checkout@v2
        with:
          ref: 'main'
      - name: Create tag
        uses: actions/github-script@v7
        with:
          script: |
            const date = new Date().toISOString().split('T')[0].replace(/-/g, '');
            const tagName = `refs/tags/${date}`;
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: tagName,
              sha: context.sha
            })
