name: Continuous Deployment
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # Runs at 00:00 UTC every day
jobs:
  build:
    runs-on: ubuntu-latest
    # required by conda
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        prefix:
          - /cvmfs/northgrid.gridpp.ac.uk/simonsobservatory/conda
          - /tmp
    steps:
    - name: Set date
      run: echo "TODAYS_DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV
    - uses: actions/checkout@v4
    - name: mkdir and chown
      run: |
        sudo mkdir -p ${{ matrix.prefix }}
        sudo chown -R $USER ${{ matrix.prefix }}
    - uses: conda-incubator/setup-miniconda@v2
      with:
        mamba-version: "*"
        channels: conda-forge
        activate-environment: ${{ matrix.prefix }}/so-conda-${{ env.TODAYS_DATE }}
        environment-file: examples/so.yml
    - name: cleanup
      run: mamba clean --all
    - name: debug
      run: ls -R ${{ matrix.prefix }}
    - name: create tarball
      run: |
        cd ${{ matrix.prefix }}
        tar -cf so-conda.tar so-conda-${{ env.TODAYS_DATE }}
        gzip so-conda.tar
    - name: debug
      run: ls ${{ matrix.prefix }}
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ matrix.prefix }}/so-conda.tar.gz
        tag_name: ${{ env.TODAYS_DATE }}
        name: ${{ env.TODAYS_DATE }}
