name: Continuous Deployment
on:
  # https://stackoverflow.com/a/61892639/5769446
  push:
    tags:
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest
    # required by conda
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        prefix:
          - /cvmfs/northgrid.gridpp.ac.uk/simonsobservatory/conda/
    steps:
    - uses: actions/checkout@v4
    - uses: conda-incubator/setup-miniconda@v2
      with:
        mamba-version: "*"
        channels: conda-forge
        auto-activate-base: true
        activate-environment: ""
    - name: mkdir and chown
      run: |
        sudo mkdir -p ${{ matrix.prefix }}
        sudo chown -R $USER ${{ matrix.prefix }}
    - name: conda create
      run: mamba env create --prefix ${{ matrix.prefix }}/so-conda-${GITHUB_REF_NAME} --file examples/so.yml
    - name: debug
      run: ls -R ${{ matrix.prefix }}
    - name: create tarball
      run: |
        cd ${{ matrix.prefix }}
        tar -cf so-conda.tar so-conda-${GITHUB_REF_NAME}
        gzip so-conda.tar
    - name: debug
      run: ls ${{ matrix.prefix }}
    - uses: actions/upload-artifact@v3
      with:
        path: ${{ matrix.prefix }}/so-conda.tar.gz
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ matrix.prefix }}/so-conda.tar.gz
