name: Continuous Deployment
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # Runs at 00:00 UTC every day
env:
  # this is the prefix for the conda environment, e.g. so-conda-YYYYMMDD
  ENV_PREFIX: so-conda
  ENV_FILE: examples/so.yml
jobs:
  build:
    runs-on: ubuntu-latest
    # required by conda
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        # this is the base prefix of the conda environment, the final conda prefix is /$BASE_PREFIX/$ENV_PREFIX-$YYYYMMDD
        BASE_PREFIX:
          - cvmfs/northgrid.gridpp.ac.uk/simonsobservatory/conda
          - tmp
    steps:
    - name: Set date and output filename
      run: |
        YYYYMMDD="$(date +'%Y%m%d')"
        echo "YYYYMMDD=$YYYYMMDD" >> $GITHUB_ENV
        FILENAME="$(echo ${{ matrix.BASE_PREFIX }} | sed 's/\//_/g'))"
        echo "FILENAME=$FILENAME" >> $GITHUB_ENV
    - uses: actions/checkout@v4
    - name: mkdir and chown
      run: |
        sudo mkdir -p /${{ matrix.BASE_PREFIX }}
        sudo chown -R $USER /${{ matrix.BASE_PREFIX }}
    - uses: conda-incubator/setup-miniconda@v2
      with:
        mamba-version: "*"
        channels: conda-forge
        activate-environment: /${{ matrix.BASE_PREFIX }}/${{ env.ENV_PREFIX }}-${{ env.YYYYMMDD }}
        environment-file: ${{ env.ENV_FILE }}
    - name: cleanup
      run: mamba clean --all
    - name: debug
      run: ls -R /${{ matrix.BASE_PREFIX }}
    - name: create tarball
      run: |
        cd /${{ matrix.BASE_PREFIX }}
        tar -cf ${{ env.FILENAME }}.tar ${{ env.ENV_PREFIX }}-${{ env.YYYYMMDD }}
        gzip ${{ env.FILENAME }}.tar
    - name: debug
      run: ls /${{ matrix.BASE_PREFIX }}
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: /${{ matrix.BASE_PREFIX }}/{{ env.FILENAME }}.tar.gz
        tag_name: ${{ env.YYYYMMDD }}
        name: ${{ env.YYYYMMDD }}
