name: Continuous Deployment
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # Runs at 00:00 UTC every day
env:
  #* this is the prefix for the conda environment, e.g. so-conda-YYYYMMDD
  #* convention: no underscores, and
  #* it should leads to unqiue filenames in the end,
  #* which means this should be unique between different kinds of builds
  ENV_PREFIX: so-conda
  ENV_FILE: examples/so.yml
jobs:
  build:
    runs-on: ubuntu-latest
    # required by conda
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        #* this is the base prefix of the conda environment,
        #* the final conda prefix is /$BASE_PREFIX/$ENV_PREFIX-$YYYYMMDD
        #* convention: no underscores, and
        #* it should leads to unqiue filenames in the end,
        #* which means this should be unique between different kinds of builds
        BASE_PREFIX:
          - cvmfs/northgrid.gridpp.ac.uk/simonsobservatory/conda
          - tmp
        python-version:
          - '3.8'
          - '3.9'
          - '3.10'
          # - '3.11'
          # - '3.12'
    steps:
    - name: Set YYYYMMDD & FILENAME; mkdir & chown
      run: |
        # use UTC time to match GitHub Actions
        YYYYMMDD="$(TZ=UTC date +'%Y%m%d')"
        echo "YYYYMMDD=$YYYYMMDD" >> $GITHUB_ENV
        ENV_NAME="${{ env.ENV_PREFIX }}-py$(echo ${{ matrix.python-version }} | sed 's/\.//')-$YYYYMMDD"
        echo "ENV_NAME=$ENV_NAME" >> $GITHUB_ENV
        FILENAME="$(echo ${{ matrix.BASE_PREFIX }} | sed 's/\//_/g')_$ENV_NAME"
        echo "FILENAME=$FILENAME" >> $GITHUB_ENV
        sudo mkdir -p /${{ matrix.BASE_PREFIX }}
        sudo chown -R $USER /${{ matrix.BASE_PREFIX }}
    - uses: actions/checkout@v4
    - uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python-version }}
        mamba-version: "*"
        channels: conda-forge
        activate-environment: /${{ matrix.BASE_PREFIX }}/${{ env.ENV_NAME }}
        environment-file: ${{ env.ENV_FILE }}
    - name: Create tarball
      run: |
        cd /${{ matrix.BASE_PREFIX }}/${{ env.ENV_NAME }}
        tar --create --use-compress-program="xz -9 -T0" --file ../${{ env.FILENAME }}.tar.xz .
        tar --create --use-compress-program="zstd -19 -T0" --file ../${{ env.FILENAME }}.tar.zst .
    - name: Deploy to GitHub Releases
      uses: softprops/action-gh-release@v1
      with:
        files: |
          /${{ matrix.BASE_PREFIX }}/${{ env.FILENAME }}.tar.xz
          /${{ matrix.BASE_PREFIX }}/${{ env.FILENAME }}.tar.zst
        tag_name: ${{ env.YYYYMMDD }}
        name: ${{ env.YYYYMMDD }}
