name: Continuous Deployment
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    # required by conda
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        prefix:
          - /cvmfs/northgrid.gridpp.ac.uk/simonsobservatory/conda/
    steps:
    - name: Set date
      run: echo "TODAYS_DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV
    - uses: actions/checkout@v4
    - uses: conda-incubator/setup-miniconda@v2
      with:
        mamba-version: "*"
        channels: conda-forge
        auto-activate-base: true
        activate-environment: ""
    - name: mkdir and chown
      run: |
        sudo mkdir -p ${{ matrix.prefix }}
        sudo chown -R $USER ${{ matrix.prefix }}
    - name: conda create
      run: mamba env create --prefix ${{ matrix.prefix }}/so-conda-${TODAYS_DATE} --file examples/so.yml
    - name: debug
      run: ls -R ${{ matrix.prefix }}
    - uses: actions/upload-artifact@v3
      with:
        path: ${{ matrix.prefix }}
